## Bot info
gluqe:
  token: ""
  prefix: ""

## Server info
server:
  name: ""
  id:

## Roles
roles:
  join_role:

## Channels
channels:
  welcome:
  commands:

## Colors (Hex)
colors:
  main:
  info:
  warning:
  error: