channels:
  commands:
  welcome:
  giveaway:
  moderation_log:
colors:
  error: 
  info: 
  main:
  warning: 
  welcome: 
gluqe:
  activity:
  owner:
  prefix:
  token:
panel:
  api:
  url:
roles:
  join_role:
selfroles:
  message_channel_id:
  message_id:
  roles:
  - name:
    role_id:
  - name:
    role_id:
  - name:
    role_id:
  - name:
    role_id:
server:
  id:
  name: