## Bot info
gluqe:
  token: ""
  prefix: ""
  activity:
    - ""
    - ""
    - ""

## Server info
server:
  name: ""
  id:

## Panel info
panel:
  url: ""
  api: ""

## Roles
roles:
  join_role:

## Channels
channels:
  welcome:
  commands:

## Colors (Hex)
colors:
  main:
  info:
  warning:
  error: